### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by carolynvs**
* test.docker.com has been removed by Docker and replaced with a download script. I don't know where you can even file those files anymore. ¯\_(ツ)_/¯. I'm keeping the tests commented out in case anyone wants to go spleunking. But mostly to vent some spleen. 😀 
* Fix a vet error that is making the build fail
* Updated one of the tests to use a version of docker that is still available

### CODE REVIEW

**Comment by carolynvs** [comment]
@rgbkrk When you have time, can you review and merge this one first? It fixes tests that run during CI. Once the build is green, we can safely test and merge the other PRs.

**Comment by rgbkrk** [comment]
You'll have to add me to the org in order for me to merge this. 😄

**Comment by carolynvs** [comment]
> You'll have to add me to the org in order for me to merge this.

Challenge Accepted!

**Comment by rgbkrk** [comment]
I can still only comment 😅

Looking at the permissions, I think you'll have to either add me to the repo as a collaborator or make a team that has access to this repo.

**Comment by carolynvs** [comment]
Okay how about now? I made a team called @howtowhale/dvm-maintainers and made you a captain. ⚓️

**Comment by rgbkrk** [comment]
All set! Thanks for having me aboard.

**Comment by carolynvs** [comment]
Yaarrrrrrr, thanks for merging!

**Pull request merged**
