### PR TITLE
ci: add github action flow

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by chenrui333** [comment]
cc @carolynvs this PR is ready to go.

**Comment by chenrui333** [comment]
The workflow got tested out in here, https://github.com/chenrui333/dvm/actions

**Review by carolynvs — APPROVED** [review]
Thanks for updating this to gh actions and adding support for more architectures!

**Comment by chenrui333** [comment]
This is [what](https://github.com/Homebrew/homebrew-core/blob/master/Formula%2Fdvm.rb#L19-L20) drives me in here. :)

**Comment by chenrui333** [comment]
@carolynvs can you also make a quick new release upon this merge. Many thanks!

**Comment by carolynvs** [comment]
Thanks again for the fix! I've published a 1.0.3

**Comment by chenrui333** [comment]
Nice!

**Comment by chenrui333** [comment]
🤔 somehow, I did not see it in here, https://github.com/howtowhale/dvm/releases

**Comment by carolynvs** [comment]
Sorry I accidentally tagged it as v1.0.3, when it should be 1.0.3. Fixing now should take 5 minutes. I'm also working on fixing the homebrew formula

**Comment by carolynvs** [comment]
Okay try now

**Comment by carolynvs** [comment]
Here's the homebrew pr https://github.com/Homebrew/homebrew-core/pull/96598

**Comment by carolynvs** [comment]
Okay 1.0.3 with arm support should now be up on homebrew. If it doesn't work, please let me know! I don't have a m1 to test on.

**Comment by chenrui333** [comment]
works for me, thanks!
```
$ /opt/homebrew/Cellar/dvm/1.0.3/dvm-helper/dvm-helper list-remote
1.8.0
1.8.1
1.8.2
1.8.3
1.9.0
1.9.1
1.10.0
1.10.1
1.10.2
1.10.3
1.11.0
1.8.0
1.8.1
1.8.2
1.8.3
1.9.0
1.9.1
1.10.0
1.10.1
1.10.2
1.10.3
1.11.0
```

**Pull request merged**
